### ISSUE TITLE
Question about geo registration

### ISSUE THREAD

**Issue by LEEJUHUI6635** [MIT-SPARK/Loc-NeRF#5]
Hello. Firstly, thank you for your nice research.

I have a problem about geo-registration to obtain metric units of colmap.
First, I obtained the odometry information through VINS-Fusion algorithm, and got the pose in metric units of each image. The odometry from vio.txt(from VINS-Fusion) was converted into translation of camera to world coordinate and then, I performed the geo registration of colmap. The learning seemed successful, but when actually turning the Loc-NeRF, the scale of the odometry and the scale of the NeRF map do not seem to fit. Therefore, I assume that geo registration works wrong, so I am having difficulty using the Loc-NeRF algorithm. Could you provide me information on how you provided gt pose for geo registration, and how did geo registration?

Thank you.

**Comment by Dominic101** [comment]
My first question is if the colmap poses were actually scaled correctly. Did you try plotting the scaled colmap trajectory compared to the VINS-Fusion trajectory and confirm the scale and shape of the trajectory is reasonable?

**Comment by shenyehui** [comment]
> Hello. Firstly, thank you for your nice research.
> 
> I have a problem about geo-registration to obtain metric units of colmap. First, I obtained the odometry information through VINS-Fusion algorithm, and got the pose in metric units of each image. The odometry from vio.txt(from VINS-Fusion) was converted into translation of camera to world coordinate and then, I performed the geo registration of colmap. The learning seemed successful, but when actually turning the Loc-NeRF, the scale of the odometry and the scale of the NeRF map do not seem to fit. Therefore, I assume that geo registration works wrong, so I am having difficulty using the Loc-NeRF algorithm. Could you provide me information on how you provided gt pose for geo registration, and how did geo registration?
> 
> Thank you.

can you tell me your version of gtsam? I meet this issue:AttributeError: 'gtsam.gtsam.Rot3' object has no attribute 'quaternion'
